# Generated by Django 4.2.26 on 2025-11-14 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='学校名')),
                ('student_name', models.CharField(max_length=100, verbose_name='生徒名')),
                ('teacher_name', models.CharField(max_length=100, verbose_name='教師名')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('tags', models.ManyToManyField(blank=True, to='ssk_app.tag', verbose_name='タグ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='授業内容')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(verbose_name='授業日')),
                ('status', models.CharField(choices=[('pending', '未開始'), ('scheduled', '参加予定'), ('attended', '出席済み'), ('absent', '欠席'), ('completed', '完了')], default='pending', max_length=10, verbose_name='進歩')),
                ('note', models.TimeField(verbose_name='特記事項')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssk_app.student', verbose_name='生徒名')),
            ],
        ),
    ]
